### ISSUE TITLE
TCompactProtocol

### ISSUE THREAD

**Issue by allenlikeu** [wadey/node-thrift#30]
I used TCompactProtocol in my data port project, which was written in Python.

Now, I am building a game server while using the pomelo framework.

Unfortunately, I found that this node-thrift module did not support TCompactProtocol. 

And, I am fresh in nodejs, I am unable to rewrite the TCompactProtocol in nodejs.

Can someone rewrite this?

**Comment by wadey** [comment]
Please report this upstream to Apache Thrift: http://thrift.apache.org/
